# Generated by Django 4.1.4 on 2023-01-15 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_blog_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.ManyToManyField(related_name='user_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
