# Generated by Django 4.1.4 on 2023-01-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_alter_replay_comment_delete_coomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay',
            old_name='replay',
            new_name='text',
        ),
    ]
